### ISSUE TITLE
(slightly) relevant - .binFBX Format

### ISSUE THREAD

**Issue by riverence** [Remedy-Entertainment/usdFBX#5]
hey hey! is this the same format used for Alan Wake 2 assets? would one (theoretically) be able to use this repository to help reverse engineer the binfbx format to help import/export meshes and assets for the sake of mods? please let me know if this does not belong here or if it violates some copyright laws or something; i wanted to contact Kristof personally but his linked twitter is inactive and has DMs off :(

**Comment by kminnaert** [comment]
Hi @riverence ,

We did not use this repository for Alan Wake 2 and I can unfortunately not disclose any details about .binfbx, apologies.
